import{a as O,S as L,i as a}from"./assets/vendor-BMHzDZyJ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&s(m)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const H="https://pixabay.com/api/",A="50360143-67f83f4bf6f92da79a63477ea";async function b(r,t){try{return(await O.get(H,{params:{key:A,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}catch(i){throw i}}const p=document.querySelector(".gallery"),n=document.querySelector(".loader"),c=document.querySelector(".more-btn");let l;function w(r){const t=r.map(({webformatURL:i,largeImageURL:s,tags:e,likes:o,views:m,comments:D,downloads:M})=>`<li class="item-image">
        <a href="${s}">
          <img class="image" src="${i}" alt="${e}">
        </a>
        <div class="info">
          <p class="info-item"><span>Likes</span> ${o}</p>
          <p class="info-item"><span>Views</span> ${m}</p>
          <p class="info-item"><span>Comments</span> ${D}</p>
          <p class="info-item"><span>Downloads</span> ${M}</p>
        </div>
      </li>`).join(`
`);p.insertAdjacentHTML("beforeend",t),l?l.refresh():l=new L(".gallery a",{captionsData:"alt",captionsPosition:"bottom",captionsDelay:250})}function P(){n==null||n.classList.remove("hidden")}function v(){n==null||n.classList.add("hidden")}function B(){p&&(p.innerHTML="",l&&(l.destroy(),l=null))}function q(){c==null||c.classList.remove("hidden")}function f(){c==null||c.classList.add("hidden")}const y=document.querySelector(".form"),F=document.querySelector(".more-btn"),u=document.querySelector(".js-loader");new L(".gallery a",{captionsData:"alt",captionDelay:250});let d=1,h,T=15,g;y.addEventListener("submit",async r=>{r.preventDefault(),B(),f();const t=r.target.elements["search-text"].value.trim();if(t===""){a.info({title:"",message:"Please enter a search term to find images.",position:"topRight",timeout:3e3});return}g=t,d=1,P(),S();try{const i=await b(g,d),s=i.hits,e=i.totalHits;if(s.length===0){a.warning({title:"Sorry",message:"There are no images matching your search query. Please try again!",position:"topRight",timeout:3e3});return}h=Math.ceil(e/T),w(s),y.reset(),x(),d>=h?(a.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3}),f()):q()}catch{a.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight",timeout:3e3})}finally{v(),R()}});F.addEventListener("click",async()=>{d+=1,f(),P(),S();try{const t=(await b(g,d)).hits;if(w(t),x(),d>=h){a.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3}),f();return}q()}catch{a.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight",timeout:3e3})}finally{v(),R()}});function S(){u==null||u.classList.add("load-spinner")}function R(){u==null||u.classList.remove("load-spinner")}function x(){const r=document.querySelector(".item-image");if(r){const t=r.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
